Vagrant.configure("2") do |config|

  config.vm.define :firewalled do |vmconfig|
    vmconfig.vm.box = "firewalled"
    vmconfig.vm.box_url = "http://cloud-images.ubuntu.com/vagrant/raring/current/raring-server-cloudimg-amd64-vagrant-disk1.box"
    vmconfig.vm.network :private_network, ip: "10.2.2.10"

    vmconfig.vm.provision :ansible do |ansible|
      ansible.playbook = "firewalled.yml"
      ansible.inventory_path = "hosts"
    end
  end

end
