Vagrant.configure("2") do |config|

  config.vm.define :simple_site do |vmconfig|
    vmconfig.vm.box = "simple_site"
    vmconfig.vm.box_url = "http://cloud-images.ubuntu.com/vagrant/raring/current/raring-server-cloudimg-amd64-vagrant-disk1.box"
    vmconfig.vm.network :private_network, ip: "10.1.1.10"

    vmconfig.vm.provision :ansible do |ansible|
      ansible.playbook = "simple_site.yml"
      ansible.inventory_path = "hosts"
    end
  end

end